In [1]:
from google.colab import drive
drive.mount("/gdrive", force_remount=True)

Mounted at /gdrive


In [65]:
import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import accuracy_score

# 데이터 읽기 함수
def load_dataset(file):
  data = np.loadtxt(file)
  print("DATA=",data)
  
  input_features = data[:,0:-1]
  print("X=",input_features)
  
  labels = np.reshape(data[:,-1],(4,1)) #1행 4열을 reshape를 통해 4행 1열로 바꾼다.
  print("Y=",labels)

 #tensor - 고차원 array
 #tensor로 바꾸는 이유 - pythorch 입력이 tensor
  input_features = torch.tensor(input_features, dtype=torch.float) 
  labels = torch.tensor(labels, dtype=torch.float)

  return (input_features, labels)

# 모델 평가 결과 계산을 위해 텐서를 리스트로 변환하는 함수
#tensor는 읽기 힘드므로 list로 변경해서 읽기
def tensor2list(input_tensor):
    return input_tensor.cpu().detach().numpy().tolist()

x, y = load_dataset("/gdrive/My Drive/colab/ann/xor/train.txt")

# layer 1 가중치 초기화
# 이곳을 완성하세요.
#bias가 필요한 이유!!!!!
#randn에서 n은 정규분포값을 바탕으로 할당하는것을 의미(정규분포 -> 평균1, )

w1 = torch.randn(2,2, requires_grad=True)
b1 = torch.randn(2, requires_grad=True)

print("\n[Init]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))

# layer 2 가중치 초기화
# 이곳을 완성하세요.

w2 = torch.randn(2,1, requires_grad=True)
b2 = torch.randn(1, requires_grad=True)

print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# Activation 함수 설정
#직접 계산하면 언더플로우나 오버플로우 발생할 확률이 있음!!
sigmoid = nn.Sigmoid()
#function포인터 - 함수를 담아둠

# 이진분류 크로스엔트로피 비용 함수 설정 
loss_func = torch.nn.BCELoss()

# 옵티마이저 함수 (역전파 알고리즘을 수행할 함수)
optimizer = torch.optim.SGD([w1,b1,w2,b2], lr=0.35)#,lr=0.2)

# 모델 학습
for epoch in range(1001):

    # H(X) 계산: forward 연산
    # 이곳을 완성하세요.
    #wx+b
    L2 = sigmoid(torch.add(torch.matmul(x,w1),b1))
    #wL+b
    hx = sigmoid(torch.add(torch.matmul(L2,w2),b2))

    # 비용 계산
    cost = loss_func(hx, y)

    # 역전파 수행
    # 값을 업데이트 시킴
    cost.backward()
    optimizer.step()

    # 100 에폭마다 비용 출력
    if epoch % 100 == 0:
        print(epoch, cost.item())

print("\n[Learned]\nw1 = {0}".format(tensor2list(w1)))
print("b1 = {0}".format(tensor2list(b1)))
print("w2 = {0}".format(tensor2list(w2)))
print("b2 = {0}\n".format(tensor2list(b2)))

# 모델 평가
# H(X) 계산: forward 연산
# 이곳을 완성사에요.
#wx+b
L2 = sigmoid(torch.add(torch.matmul(x,w1),b1))
#wL+b
hx = sigmoid(torch.add(torch.matmul(L2,w2),b2))

#logits이라는 단어 알아두기!!
logits = (hx > 0.5).float()
predicts = tensor2list(logits)
golds = tensor2list(y)

print("\nPRED=",predicts)
print("GOLD=",golds)
print("Accuracy : {0:f}".format(accuracy_score(golds, predicts)))

DATA= [[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
X= [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Y= [[0.]
 [1.]
 [1.]
 [0.]]

[Init]
w1 = [[2.240201711654663, 2.0275979042053223], [-0.2568914294242859, -0.32581740617752075]]
b1 = [1.438533067703247, -0.9961214065551758]
w2 = [[-1.4341288805007935], [0.715241551399231]]
b2 = [-0.0748797133564949]

0 0.8058335185050964
100 0.002238964894786477
200 0.0
300 0.0
400 0.0
500 0.0
600 0.0
700 0.0
800 0.0
900 0.0
1000 0.0

[Learned]
w1 = [[253.77456665039062, 217.19041442871094], [-256.9891052246094, -241.94664001464844]]
b1 = [69.43267059326172, -40.078556060791016]
w2 = [[-292.26708984375], [409.10394287109375]]
b2 = [194.4167022705078]


PRED= [[0.0], [1.0], [1.0], [0.0]]
GOLD= [[0.0], [1.0], [1.0], [0.0]]
Accuracy : 1.000000
